# Generated by Django 3.2.3 on 2021-06-09 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsApp', '0004_auto_20210609_2358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='customer',
        ),
        migrations.AddField(
            model_name='customer',
            name='location',
            field=models.ManyToManyField(to='NewsApp.Location'),
        ),
    ]
