# Generated by Django 3.2.3 on 2021-06-09 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsApp', '0007_auto_20210610_0041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='name',
        ),
        migrations.AddField(
            model_name='location',
            name='location_name',
            field=models.CharField(choices=[('Anand', 'Anand'), ('Gandhinagar', 'Gandhinagar'), ('Surat', 'Surat'), ('Baroda', 'Baroda'), ('Ahmedabad', 'Ahmedabad')], max_length=200, null=True),
        ),
    ]
