# Generated by Django 3.2.3 on 2021-06-09 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsApp', '0011_customer_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(choices=[('Anand', 'Anand'), ('Gandhinagar', 'Gandhinagar'), ('Surat', 'Surat'), ('Baroda', 'Baroda'), ('Ahmedabad', 'Ahmedabad')], max_length=200, null=True)),
            ],
        ),
    ]
