# Generated by Django 3.2.3 on 2021-06-09 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsApp', '0013_auto_20210610_0150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='location',
        ),
        migrations.AddField(
            model_name='customer',
            name='location',
            field=models.CharField(choices=[('Anand', 'Anand'), ('Gandhinagar', 'Gandhinagar'), ('Surat', 'Surat'), ('Baroda', 'Baroda'), ('Ahmedabad', 'Ahmedabad')], max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
