# Generated by Django 3.2.3 on 2021-06-09 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NewsApp', '0014_auto_20210610_0151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='user',
        ),
    ]
