# Generated by Django 3.2.3 on 2021-06-10 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsApp', '0018_alter_customer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='language',
            field=models.CharField(choices=[('English', 'English'), ('Hindi', 'Hindi'), ('Gujarati', 'Gujarati')], default='Gujarati', max_length=200),
        ),
        migrations.AlterField(
            model_name='customer',
            name='location',
            field=models.CharField(choices=[('Anand', 'Anand'), ('Gandhinagar', 'Gandhinagar'), ('Surat', 'Surat'), ('Baroda', 'Baroda'), ('Ahmedabad', 'Ahmedabad')], default='Gandhinagar', max_length=200),
        ),
    ]
