# Generated by Django 3.2.3 on 2021-06-10 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsApp', '0019_auto_20210610_1412'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='language',
        ),
        migrations.AlterField(
            model_name='customer',
            name='location',
            field=models.CharField(choices=[('at', 'Austria'), ('be', 'Belgium'), ('bg', 'Bulgaria'), ('in', 'India')], default='at', max_length=200),
        ),
    ]
