# Generated by Django 3.2.3 on 2021-06-10 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsApp', '0020_auto_20210610_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='location',
            field=models.CharField(choices=[('at', 'Austria'), ('au', 'Australia'), ('be', 'Belgium'), ('bg', 'Bulgaria'), ('ca', 'Canada'), ('cn', 'China'), ('de', 'Germany'), ('eg', 'Egypt'), ('fn', 'France'), ('gr', 'Greece'), ('in', 'India'), ('lt', 'Lithuania'), ('mx', 'Mexico'), ('nl', 'Netherlands'), ('se', 'Sweden'), ('sg', 'Singapore'), ('si', 'Slovenia'), ('ru', 'Russia')], default='in', max_length=200),
        ),
    ]
