# Generated by Django 3.1.7 on 2021-06-28 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsApp', '0021_alter_customer_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='location',
            field=models.CharField(choices=[('at', 'Austria'), ('au', 'Australia'), ('be', 'Belgium'), ('bg', 'Bulgaria'), ('ca', 'Canada'), ('de', 'Germany'), ('eg', 'Egypt'), ('fn', 'France'), ('gr', 'Greece'), ('in', 'India'), ('lt', 'Lithuania'), ('nl', 'Netherlands'), ('se', 'Sweden'), ('sg', 'Singapore'), ('si', 'Slovenia'), ('ru', 'Russia')], default='in', max_length=200),
        ),
    ]
